=== Nana-Lv/TF_SPLERGE/ICDAR2013_table_dataset/us-gov-dataset/competition-entry-structure-model.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="document">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="table" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="region" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element maxOccurs="unbounded" name="cell">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="bounding-box" minOccurs="0" maxOccurs="1"> <!-- the bounding box is optional -->
                                                        <xsd:complexType>
                                                            <xsd:attribute name="x1" type="xsd:integer" use="required"/>
                                                            <xsd:attribute name="y1" type="xsd:integer" use="required"/>
                                                            <xsd:attribute name="x2" type="xsd:integer" use="required"/>
                                                            <xsd:attribute name="y2" type="xsd:integer" use="required"/>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="content" type="xsd:string" minOccurs="1"/>
                                                    <xsd:element name="instruction" minOccurs="0" maxOccurs="unbounded"> <!-- the instructions are optional -->
                                                        <xsd:complexType>
                                                            <xsd:attribute name="instr-id" type="xsd:integer" use="required"/>
                                                            <xsd:attribute name="subinstr-id" type="xsd:integer"/>
                                                        <!--<xsd:attribute name="text" type="xsd:string" use="required"/>
                                                            <xsd:attribute name="x1" type="xsd:integer" use="required"/>
                                                            <xsd:attribute name="y1" type="xsd:integer" use="required"/>
                                                            <xsd:attribute name="x2" type="xsd:integer" use="required"/>
                                                            <xsd:attribute name="y2" type="xsd:integer" use="required"/>-->
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                                <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
                                                <xsd:attribute name="start-col" type="xsd:nonNegativeInteger" use="required"/>
                                                <xsd:attribute name="start-row" type="xsd:nonNegativeInteger" use="required"/>
                                                <xsd:attribute name="end-col" type="xsd:nonNegativeInteger"/>
                                                <xsd:attribute name="end-row" type="xsd:nonNegativeInteger"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
                                    <xsd:attribute name="page" type="xsd:positiveInteger" use="required"/>
                                    <xsd:attribute name="col-increment" type="xsd:integer"/>
                                    <xsd:attribute name="row-increment" type="xsd:integer"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="filename" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Nana-Lv/TF_SPLERGE/ICDAR2013_table_dataset/eu-dataset/eu-006-str.xml
<?xml version="1.0" encoding="UTF-8"?>
<document filename="eu-006.pdf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="competition-entry-structure-model.xsd">
    <table id="0">
        <region col-increment="0" id="0" page="3" row-increment="0">
            <cell id="0" start-col="0" start-row="0">
                <bounding-box x1="104" x2="147" y1="398" y2="410"/>
                <content>Country</content>
                <instruction instr-id="1621" subinstr-id="0"/>
            </cell>
            <cell id="1" start-col="1" start-row="0">
                <bounding-box x1="231" x2="307" y1="398" y2="410"/>
                <content>Student grants</content>
                <instruction instr-id="1621" subinstr-id="2"/>
            </cell>
            <cell id="2" start-col="2" start-row="0">
                <bounding-box x1="408" x2="469" y1="398" y2="410"/>
                <content>Tuition fees</content>
                <instruction instr-id="1621" subinstr-id="4"/>
            </cell>
            <cell id="3" start-col="0" start-row="1">
                <bounding-box x1="70" x2="115" y1="383" y2="395"/>
                <content>Denmark</content>
                <instruction instr-id="1634" subinstr-id="0"/>
                <instruction instr-id="1634" subinstr-id="2"/>
            </cell>
            <cell id="4" start-col="1" start-row="1">
                <bounding-box x1="327" x2="351" y1="383" y2="395"/>
                <content>3750</content>
                <instruction instr-id="1634" subinstr-id="2"/>
            </cell>
            <cell id="5" start-col="2" start-row="1">
                <bounding-box x1="515" x2="521" y1="383" y2="395"/>
                <content>0</content>
                <instruction instr-id="1634" subinstr-id="4"/>
            </cell>
            <cell id="6" start-col="0" start-row="2">
                <bounding-box x1="70" x2="112" y1="368" y2="380"/>
                <content>Flanders</content>
                <instruction instr-id="1646" subinstr-id="0"/>
            </cell>
            <cell id="7" start-col="1" start-row="2">
                <bounding-box x1="333" x2="351" y1="368" y2="380"/>
                <content>342</content>
                <instruction instr-id="1646" subinstr-id="0"/>
            </cell>
            <cell id="8" start-col="2" start-row="2">
                <bounding-box x1="481" x2="521" y1="368" y2="380"/>
                <content>100-600</content>
                <instruction instr-id="1646" subinstr-id="2"/>
            </cell>
            <cell id="9" start-col="0" start-row="3">
                <bounding-box x1="70" x2="103" y1="354" y2="366"/>
                <content>France</content>
                <instruction instr-id="1658" subinstr-id="0"/>
            </cell>
            <cell id="10" start-col="1" start-row="3">
                <bounding-box x1="333" x2="351" y1="354" y2="366"/>
                <content>494</content>
                <instruction instr-id="1658" subinstr-id="0"/>
            </cell>
            <cell id="11" start-col="2" start-row="3">
                <bounding-box x1="481" x2="521" y1="354" y2="366"/>
                <content>200-850</content>
                <instruction instr-id="1658" subinstr-id="2"/>
            </cell>
            <cell id="12" start-col="0" start-row="4">
                <bounding-box x1="70" x2="115" y1="340" y2="352"/>
                <content>Germany</content>
                <instruction instr-id="1669" subinstr-id="0"/>
                <instruction instr-id="1669" subinstr-id="2"/>
            </cell>
            <cell id="13" start-col="1" start-row="4">
                <bounding-box x1="333" x2="351" y1="340" y2="352"/>
                <content>374</content>
                <instruction instr-id="1669" subinstr-id="2"/>
            </cell>
            <cell id="14" start-col="2" start-row="4">
                <bounding-box x1="515" x2="521" y1="340" y2="352"/>
                <content>0</content>
                <instruction instr-id="1669" subinstr-id="4"/>
            </cell>
            <cell id="15" start-col="0" start-row="5">
                <bounding-box x1="70" x2="128" y1="326" y2="338"/>
                <content>Netherlands</content>
                <instruction instr-id="1681" subinstr-id="0"/>
            </cell>
            <cell id="16" start-col="1" start-row="5">
                <bounding-box x1="327" x2="351" y1="326" y2="338"/>
                <content>1750</content>
                <instruction instr-id="1681" subinstr-id="0"/>
            </cell>
            <cell id="17" start-col="2" start-row="5">
                <bounding-box x1="497" x2="521" y1="326" y2="338"/>
                <content>1300</content>
                <instruction instr-id="1681" subinstr-id="2"/>
            </cell>
            <cell id="18" start-col="0" start-row="6">
                <bounding-box x1="70" x2="108" y1="311" y2="323"/>
                <content>Sweden</content>
                <instruction instr-id="1692" subinstr-id="0"/>
            </cell>
            <cell id="19" start-col="1" start-row="6">
                <bounding-box x1="327" x2="351" y1="311" y2="323"/>
                <content>2150</content>
                <instruction instr-id="1692" subinstr-id="0"/>
            </cell>
            <cell id="20" start-col="2" start-row="6">
                <bounding-box x1="515" x2="521" y1="311" y2="323"/>
                <content>0</content>
                <instruction instr-id="1692" subinstr-id="2"/>
            </cell>
            <cell id="21" start-col="0" start-row="7">
                <bounding-box x1="70" x2="151" y1="297" y2="309"/>
                <content>United Kingdom</content>
                <instruction instr-id="1704" subinstr-id="0"/>
            </cell>
            <cell id="22" start-col="1" start-row="7">
                <bounding-box x1="333" x2="351" y1="297" y2="309"/>
                <content>700</content>
                <instruction instr-id="1704" subinstr-id="4"/>
            </cell>
            <cell id="23" start-col="2" start-row="7">
                <bounding-box x1="497" x2="521" y1="297" y2="309"/>
                <content>1700</content>
                <instruction instr-id="1704" subinstr-id="6"/>
            </cell>
        </region>
    </table>
</document>

=== Nana-Lv/TF_SPLERGE/ICDAR2013_table_dataset/eu-dataset/eu-026-str.xml
<?xml version="1.0" encoding="UTF-8"?>
<document filename="eu-026.pdf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="competition-entry-structure-model.xsd">
    <table id="0">
        <region col-increment="0" id="0" page="3" row-increment="0">
            <cell id="0" start-col="1" start-row="0">
                <bounding-box x1="412" x2="458" y1="612" y2="628"/>
                <content>in year-on-year 
terms</content>
                <instruction instr-id="15371"/>
                <instruction instr-id="15375"/>
            </cell>
            <cell id="1" start-col="2" start-row="0">
                <bounding-box x1="470" x2="535" y1="612" y2="628"/>
                <content>in quarter-on-quarter
terms</content>
                <instruction instr-id="15379"/>
                <instruction instr-id="15383"/>
            </cell>
            <cell id="2" start-col="0" start-row="1">
                <bounding-box x1="354" x2="380" y1="599" y2="606"/>
                <content>Germany</content>
                <instruction instr-id="15390" subinstr-id="0"/>
            </cell>
            <cell id="3" start-col="1" start-row="1">
                <bounding-box x1="446" x2="458" y1="599" y2="606"/>
                <content>0.34</content>
                <instruction instr-id="15390" subinstr-id="2"/>
            </cell>
            <cell id="4" start-col="2" start-row="1">
                <bounding-box x1="523" x2="535" y1="599" y2="606"/>
                <content>0.18</content>
                <instruction instr-id="15390" subinstr-id="4"/>
            </cell>
            <cell id="5" start-col="0" start-row="2">
                <bounding-box x1="354" x2="370" y1="590" y2="597"/>
                <content>Spain</content>
                <instruction instr-id="15394" subinstr-id="0"/>
            </cell>
            <cell id="6" start-col="1" start-row="2">
                <bounding-box x1="446" x2="458" y1="590" y2="597"/>
                <content>0.75</content>
                <instruction instr-id="15394" subinstr-id="2"/>
            </cell>
            <cell id="7" start-col="2" start-row="2">
                <bounding-box x1="523" x2="535" y1="590" y2="597"/>
                <content>0.70</content>
                <instruction instr-id="15394" subinstr-id="4"/>
            </cell>
            <cell id="8" start-col="0" start-row="3">
                <bounding-box x1="354" x2="373" y1="581" y2="588"/>
                <content>France</content>
                <instruction instr-id="15398" subinstr-id="0"/>
            </cell>
            <cell id="9" start-col="1" start-row="3">
                <bounding-box x1="446" x2="458" y1="581" y2="588"/>
                <content>0.63</content>
                <instruction instr-id="15398" subinstr-id="2"/>
            </cell>
            <cell id="10" start-col="2" start-row="3">
                <bounding-box x1="523" x2="535" y1="581" y2="588"/>
                <content>0.37</content>
                <instruction instr-id="15398" subinstr-id="4"/>
            </cell>
            <cell id="11" start-col="0" start-row="4">
                <bounding-box x1="354" x2="367" y1="572" y2="579"/>
                <content>Italy</content>
                <instruction instr-id="15402" subinstr-id="0"/>
            </cell>
            <cell id="12" start-col="1" start-row="4">
                <bounding-box x1="446" x2="458" y1="572" y2="579"/>
                <content>0.60</content>
                <instruction instr-id="15402" subinstr-id="2"/>
            </cell>
            <cell id="13" start-col="2" start-row="4">
                <bounding-box x1="523" x2="535" y1="572" y2="579"/>
                <content>0.38</content>
                <instruction instr-id="15402" subinstr-id="4"/>
            </cell>
            <cell id="14" start-col="0" start-row="5">
                <bounding-box x1="354" x2="381" y1="561" y2="568"/>
                <content>Euro area</content>
                <instruction instr-id="15406" subinstr-id="0"/>
            </cell>
            <cell id="15" start-col="1" start-row="5">
                <bounding-box x1="446" x2="458" y1="561" y2="568"/>
                <content>0.72</content>
                <instruction instr-id="15406" subinstr-id="2"/>
            </cell>
            <cell id="16" start-col="2" start-row="5">
                <bounding-box x1="523" x2="535" y1="561" y2="568"/>
                <content>0.49</content>
                <instruction instr-id="15406" subinstr-id="4"/>
            </cell>
        </region>
    </table>
</document>

=== Nana-Lv/TF_SPLERGE/ICDAR2013_table_dataset/us-gov-dataset/us-009-str.xml
<?xml version="1.0" encoding="UTF-8"?>
<document filename="us-009.pdf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="competition-entry-structure-model.xsd">
    <table id="0">
        <region col-increment="0" id="0" page="2" row-increment="0">
            <cell id="0" start-col="0" start-row="0">
                <bounding-box x1="399" x2="426" y1="614" y2="628"/>
                <content>Discountrate</content>
                <instruction instr-id="998"/>
                <instruction instr-id="1000"/>
            </cell>
            <cell id="1" start-col="1" start-row="0">
                <bounding-box x1="439" x2="468" y1="614" y2="628"/>
                <content>Expected
NPV</content>
                <instruction instr-id="1002"/>
                <instruction instr-id="1004"/>
            </cell>
            <cell id="2" start-col="2" start-row="0">
                <bounding-box x1="485" x2="515" y1="607" y2="635"/>
                <content>Total
expected
PV
(benefits)</content>
                <instruction instr-id="1006"/>
                <instruction instr-id="1008"/>
                <instruction instr-id="1010"/>
                <instruction instr-id="1012"/>
            </cell>
            <cell id="3" start-col="3" start-row="0">
                <bounding-box x1="533" x2="561" y1="607" y2="635"/>
                <content>Total
expected
PV
(costs)</content>
                <instruction instr-id="1014"/>
                <instruction instr-id="1016"/>
                <instruction instr-id="1018"/>
                <instruction instr-id="1020"/>
            </cell>
            <cell id="4" start-col="0" start-row="1">
                <bounding-box x1="399" x2="426" y1="592" y2="599"/>
                <content>3%.......</content>
                <instruction instr-id="1044" subinstr-id="0"/>
                <instruction instr-id="1044" subinstr-id="2"/>
            </cell>
            <cell id="5" start-col="1" start-row="1">
                <bounding-box x1="456" x2="473" y1="592" y2="599"/>
                <content>$40.4</content>
                <instruction instr-id="1044" subinstr-id="4"/>
            </cell>
            <cell id="6" start-col="2" start-row="1">
                <bounding-box x1="502" x2="520" y1="592" y2="599"/>
                <content>$66.2</content>
                <instruction instr-id="1044" subinstr-id="6"/>
            </cell>
            <cell id="7" start-col="3" start-row="1">
                <bounding-box x1="549" x2="567" y1="592" y2="599"/>
                <content>$25.8</content>
                <instruction instr-id="1046"/>
            </cell>
            <cell id="8" start-col="0" start-row="2">
                <bounding-box x1="399" x2="426" y1="584" y2="591"/>
                <content>7 ..........</content>
                <instruction instr-id="1062" subinstr-id="0"/>
                <instruction instr-id="1062" subinstr-id="2"/>
            </cell>
            <cell id="9" start-col="1" start-row="2">
                <bounding-box x1="463" x2="473" y1="584" y2="591"/>
                <content>9.3</content>
                <instruction instr-id="1062" subinstr-id="4"/>
            </cell>
            <cell id="10" start-col="2" start-row="2">
                <bounding-box x1="506" x2="520" y1="584" y2="591"/>
                <content>22.0</content>
                <instruction instr-id="1064" subinstr-id="0"/>
            </cell>
            <cell id="11" start-col="3" start-row="2">
                <bounding-box x1="553" x2="566" y1="584" y2="591"/>
                <content>12.8</content>
                <instruction instr-id="1064" subinstr-id="2"/>
            </cell>
        </region>
    </table>
</document>

=== Nana-Lv/TF_SPLERGE/ICDAR2013_table_dataset/eu-dataset/eu-034-str.xml
<?xml version="1.0" encoding="UTF-8"?>
<document filename="eu-034.pdf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="competition-entry-structure-model.xsd">
    <table id="0">
        <region col-increment="0" id="0" page="2" row-increment="0">
            <cell id="0" start-col="0" start-row="0">
                <bounding-box x1="105" x2="174" y1="427" y2="436"/>
                <content>Reporting period</content>
                <instruction instr-id="1170" subinstr-id="0"/>
                <instruction instr-id="1170" subinstr-id="2"/>
                <instruction instr-id="1170" subinstr-id="4"/>
                <instruction instr-id="1170" subinstr-id="6"/>
                <instruction instr-id="1170" subinstr-id="8"/>
                <instruction instr-id="1170" subinstr-id="10"/>
                <instruction instr-id="1170" subinstr-id="14"/>
                <instruction instr-id="1170" subinstr-id="16"/>
                <instruction instr-id="1170" subinstr-id="18"/>
            </cell>
            <cell id="1" start-col="1" start-row="0">
                <bounding-box x1="257" x2="326" y1="427" y2="436"/>
                <content>Number of cases</content>
                <instruction instr-id="1197" subinstr-id="0"/>
                <instruction instr-id="1197" subinstr-id="2"/>
                <instruction instr-id="1197" subinstr-id="4"/>
                <instruction instr-id="1197" subinstr-id="6"/>
                <instruction instr-id="1197" subinstr-id="10"/>
                <instruction instr-id="1197" subinstr-id="12"/>
                <instruction instr-id="1197" subinstr-id="14"/>
            </cell>
            <cell id="2" start-col="2" start-row="0">
                <bounding-box x1="391" x2="496" y1="427" y2="436"/>
                <content>Reporting Member States</content>
                <instruction instr-id="1224" subinstr-id="0"/>
                <instruction instr-id="1224" subinstr-id="2"/>
                <instruction instr-id="1224" subinstr-id="4"/>
                <instruction instr-id="1224" subinstr-id="6"/>
                <instruction instr-id="1234" subinstr-id="0"/>
                <instruction instr-id="1234" subinstr-id="2"/>
                <instruction instr-id="1234" subinstr-id="6"/>
                <instruction instr-id="1234" subinstr-id="8"/>
                <instruction instr-id="1234" subinstr-id="10"/>
                <instruction instr-id="1234" subinstr-id="12"/>
                <instruction instr-id="1234" subinstr-id="14"/>
            </cell>
            <cell id="3" start-col="0" start-row="1">
                <bounding-box x1="70" x2="96" y1="414" y2="424"/>
                <content>2004*</content>
                <instruction instr-id="1280" subinstr-id="0"/>
            </cell>
            <cell id="4" start-col="1" start-row="1">
                <bounding-box x1="287" x2="297" y1="414" y2="424"/>
                <content>58</content>
                <instruction instr-id="1310" subinstr-id="0"/>
            </cell>
            <cell id="5" start-col="2" start-row="1">
                <bounding-box x1="411" x2="476" y1="414" y2="424"/>
                <content>AT, DE, HU, IT</content>
                <instruction instr-id="1339" subinstr-id="0"/>
                <instruction instr-id="1339" subinstr-id="2"/>
                <instruction instr-id="1339" subinstr-id="4"/>
                <instruction instr-id="1339" subinstr-id="8"/>
                <instruction instr-id="1339" subinstr-id="10"/>
                <instruction instr-id="1339" subinstr-id="14"/>
                <instruction instr-id="1339" subinstr-id="18"/>
                <instruction instr-id="1339" subinstr-id="20"/>
            </cell>
            <cell id="6" start-col="0" start-row="2">
                <bounding-box x1="70" x2="100" y1="402" y2="412"/>
                <content>2005**</content>
                <instruction instr-id="1382" subinstr-id="0"/>
                <instruction instr-id="1382" subinstr-id="2"/>
                <instruction instr-id="1382" subinstr-id="4"/>
                <instruction instr-id="1382" subinstr-id="6"/>
                <instruction instr-id="1382" subinstr-id="8"/>
                <instruction instr-id="1382" subinstr-id="10"/>
            </cell>
            <cell id="7" start-col="1" start-row="2">
                <bounding-box x1="287" x2="297" y1="402" y2="412"/>
                <content>72</content>
                <instruction instr-id="1412" subinstr-id="0"/>
            </cell>
            <cell id="8" start-col="2" start-row="2">
                <bounding-box x1="421" x2="467" y1="402" y2="412"/>
                <content>FR, HU, IT</content>
                <instruction instr-id="1441" subinstr-id="0"/>
                <instruction instr-id="1441" subinstr-id="2"/>
                <instruction instr-id="1441" subinstr-id="6"/>
                <instruction instr-id="1441" subinstr-id="10"/>
                <instruction instr-id="1441" subinstr-id="12"/>
            </cell>
            <cell id="9" start-col="0" start-row="3">
                <bounding-box x1="70" x2="105" y1="391" y2="400"/>
                <content>2006***</content>
                <instruction instr-id="1474" subinstr-id="0"/>
                <instruction instr-id="1474" subinstr-id="2"/>
                <instruction instr-id="1474" subinstr-id="4"/>
                <instruction instr-id="1474" subinstr-id="6"/>
                <instruction instr-id="1474" subinstr-id="8"/>
                <instruction instr-id="1474" subinstr-id="10"/>
                <instruction instr-id="1474" subinstr-id="12"/>
            </cell>
            <cell id="10" start-col="1" start-row="3">
                <bounding-box x1="289" x2="294" y1="391" y2="400"/>
                <content>2</content>
                <instruction instr-id="1503" subinstr-id="0"/>
            </cell>
            <cell id="11" start-col="2" start-row="3">
                <bounding-box x1="438" x2="450" y1="391" y2="400"/>
                <content>FR</content>
                <instruction instr-id="1533" subinstr-id="0"/>
            </cell>
            <cell id="12" start-col="0" start-row="4">
                <bounding-box x1="70" x2="111" y1="378" y2="388"/>
                <content>2007****</content>
                <instruction instr-id="1567" subinstr-id="0"/>
            </cell>
            <cell id="13" start-col="1" start-row="4">
                <bounding-box x1="287" x2="297" y1="378" y2="388"/>
                <content>39</content>
                <instruction instr-id="1597" subinstr-id="0"/>
            </cell>
            <cell id="14" start-col="2" start-row="4">
                <bounding-box x1="439" x2="448" y1="378" y2="388"/>
                <content>IT</content>
                <instruction instr-id="1627" subinstr-id="0"/>
            </cell>
        </region>
    </table>
</document>
