=== Nana-Lv/TF_SPLERGE/ICDAR2013_table_dataset/eu-dataset/competition-entry-region-model.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <xsd:element name="document">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" name="table"> <!-- a document can contain 0 or more tables -->
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="region" maxOccurs="unbounded" nillable="false"> <!-- each table must contain 1 or more regions -->
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="instruction" minOccurs="0" maxOccurs="unbounded"> <!-- the instructions are optional -->
                                            <xsd:complexType>
                                                <xsd:attribute name="instr-id" type="xsd:integer" use="required"/>
                                                <xsd:attribute name="subinstr-id" type="xsd:integer"/>
                                            <!--<xsd:attribute name="text" type="xsd:string" use="required"/>
                                                <xsd:attribute name="x1" type="xsd:integer" use="required"/>
                                                <xsd:attribute name="y1" type="xsd:integer" use="required"/>
                                                <xsd:attribute name="x2" type="xsd:integer" use="required"/>
                                                <xsd:attribute name="y2" type="xsd:integer" use="required"/>-->
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="bounding-box"> <!-- each region contains one bounding box -->
                                            <xsd:complexType>
                                                <xsd:attribute name="x1" type="xsd:integer" use="required"/>
                                                <xsd:attribute name="y1" type="xsd:integer" use="required"/>
                                                <xsd:attribute name="x2" type="xsd:integer" use="required"/>
                                                <xsd:attribute name="y2" type="xsd:integer" use="required"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
                                    <xsd:attribute name="page" type="xsd:positiveInteger" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="filename" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Nana-Lv/TF_SPLERGE/ICDAR2013_table_dataset/eu-dataset/eu-033-reg.xml
<?xml version="1.0" encoding="UTF-8"?>
<document filename="eu-033.pdf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="competition-entry-region-model.xsd">
    <table id="0">
        <region id="0" page="1">
            <instruction instr-id="329"/>
            <instruction instr-id="333"/>
            <instruction instr-id="336"/>
            <instruction instr-id="339"/>
            <instruction instr-id="342"/>
            <instruction instr-id="345"/>
            <instruction instr-id="348"/>
            <instruction instr-id="352" subinstr-id="0"/>
            <instruction instr-id="352" subinstr-id="2"/>
            <instruction instr-id="356"/>
            <instruction instr-id="360" subinstr-id="0"/>
            <instruction instr-id="360" subinstr-id="2"/>
            <instruction instr-id="360" subinstr-id="4"/>
            <instruction instr-id="363"/>
            <instruction instr-id="366" subinstr-id="0"/>
            <instruction instr-id="366" subinstr-id="2"/>
            <instruction instr-id="366" subinstr-id="4"/>
            <instruction instr-id="370"/>
            <instruction instr-id="372"/>
            <instruction instr-id="375"/>
            <instruction instr-id="378"/>
            <instruction instr-id="381"/>
            <instruction instr-id="412" subinstr-id="0"/>
            <instruction instr-id="412" subinstr-id="2"/>
            <instruction instr-id="412" subinstr-id="4"/>
            <instruction instr-id="412" subinstr-id="6"/>
            <instruction instr-id="412" subinstr-id="8"/>
            <instruction instr-id="412" subinstr-id="10"/>
            <instruction instr-id="412" subinstr-id="12"/>
            <instruction instr-id="439" subinstr-id="0"/>
            <instruction instr-id="439" subinstr-id="2"/>
            <instruction instr-id="439" subinstr-id="4"/>
            <instruction instr-id="439" subinstr-id="6"/>
            <instruction instr-id="439" subinstr-id="8"/>
            <instruction instr-id="439" subinstr-id="10"/>
            <instruction instr-id="464" subinstr-id="0"/>
            <instruction instr-id="464" subinstr-id="2"/>
            <instruction instr-id="464" subinstr-id="4"/>
            <instruction instr-id="464" subinstr-id="6"/>
            <instruction instr-id="464" subinstr-id="8"/>
            <instruction instr-id="464" subinstr-id="10"/>
            <instruction instr-id="489" subinstr-id="0"/>
            <instruction instr-id="489" subinstr-id="2"/>
            <instruction instr-id="489" subinstr-id="4"/>
            <instruction instr-id="489" subinstr-id="6"/>
            <instruction instr-id="489" subinstr-id="8"/>
            <instruction instr-id="489" subinstr-id="10"/>
            <instruction instr-id="514" subinstr-id="0"/>
            <instruction instr-id="514" subinstr-id="2"/>
            <instruction instr-id="514" subinstr-id="4"/>
            <instruction instr-id="514" subinstr-id="6"/>
            <instruction instr-id="514" subinstr-id="8"/>
            <instruction instr-id="514" subinstr-id="10"/>
            <instruction instr-id="539" subinstr-id="0"/>
            <instruction instr-id="539" subinstr-id="2"/>
            <instruction instr-id="539" subinstr-id="4"/>
            <instruction instr-id="539" subinstr-id="6"/>
            <instruction instr-id="539" subinstr-id="8"/>
            <instruction instr-id="539" subinstr-id="10"/>
            <instruction instr-id="569"/>
            <instruction instr-id="572" subinstr-id="2"/>
            <instruction instr-id="572" subinstr-id="4"/>
            <instruction instr-id="572" subinstr-id="6"/>
            <instruction instr-id="572" subinstr-id="8"/>
            <instruction instr-id="572" subinstr-id="10"/>
            <bounding-box x1="79" x2="519" y1="167" y2="391"/>
        </region>
    </table>
</document>
